Update README-ru.md
JunkFood02/Seal pull request #1227
Opened 2023-12-16 17:03 UTC by girshcatt

2023-12-16 19:06 UTC, JunkFood02 requested changes

2023-12-16 19:06 UTC, JunkFood02 commented on README-ru.md
> +<p><!-- sponsors --><a href="https://github.com/4kaimar"><img src="https://github.com/4kaimar.png" width="60px" alt="" /></a><a href="https://github.com/gordongw"><img src="https://github.com/gordong
https://github.com/JunkFood02/Seal/pull/1209#issuecomment-1858844372

2023-12-16 19:20 UTC, girshcatt commented
Do you mean that will be better if we remove sponsors section in readme ru?

2023-12-16 20:30 UTC, JunkFood02 commented
Yes, see https://github.com/JunkFood02/Seal/pull/1209/commits/9190dd28a9da22be7c7998d120e0084a23aa8353

2023-12-23 16:40 UTC, girshcatt commented
I did the changes for sponsor section, merge pr please

2023-12-23 18:48 UTC, merged